// Generated by packages/app-templates/scripts/executor-intro.ts. Do not edit.

/** SHA-256 of each file the Executor app publishes as a skill, keyed by `<skill>/<file>`. */
export const executorSkillDigests: Readonly<Record<string, string>> = {
  "app-authoring/SKILL.md": "350200a92d4499060fa0b4facee96de4ffdd86d64487c27c9ad3c5466821354a",
  "app-authoring/accounts.md": "47876fe2d80446d1156f042b9801eceb810925c2a195edced7980883f42d2907",
  "app-authoring/deploy.md": "b5921d1ac23d11255ccd57f2c69ed28ed5fdaa55f4bc1bd3401be55b50d64835",
  "app-authoring/events.md": "202bde87c2320af9706828063c6aaeeac0c9b8661971f610220f2a49293e3561",
  "app-authoring/integrations.md": "d4faaa7ce6324e35b1b0a52a017996aa1823696c7618333e1f0885e86b393ff5",
  "app-authoring/starter.md": "3e5b2f55da9aed2a6c0ff95d4c1982d1da6aa206fd404d6b5f1fb0b7c2880077",
  "app-authoring/storage.md": "4a305611c9c8ac31b799400fd512c3269be7289007c9679fd3eef27127859b12",
  "app-authoring/tools.md": "7ca37851e6366cb5e25f834f425813aebcaa1c944ec16082964d5319913a9cfc",
  "app-authoring/ui.md": "ac9751f5f45b0196e46e1deffa09cb302c7e43099bcc247ec455f8808b539542",
  "app-authoring/webhooks.md": "b7f43ad7af7fe1093cdc957cdec5f43bc98115d3c3237af1788cdd68d7fd9fce",
  "app-authoring/workflows.md": "9e517eaf6f461ac07fd2d29a03f0d545e79cfcbcfedbed5b8432e7b41392257b",
  "code-mode/SKILL.md": "9a29d404836ccf944b63f355a482e0db61b3434003907fe9a9a436a5b5a10959",
  "executor/SKILL.md": "580e2e296e8665c950d41197e4bf2df639be12f6ee3ec8ce51d27129dd0774ff",
  "executor/feedback.md": "11397bd260917e5a21e92897a19368d0426bf5944a7c081adc2c061d1ea797cd"
};
